[
  {
    name: "מונסטרה",
    variations: [{ variation: { גובה: "70" }, cost_per_item: "80" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "מונסטרה",
    image_path: "image_מונסטרה.jpeg",
  },
  {
    name: "היוקקקטוס",
    variations: [{ variation: { גובה: "1.65" }, cost_per_item: "375" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "היוקקקטוס",
    image_path: "image_היוקקקטוס.jpeg",
  },
  {
    name: "יוקה",
    variations: [{ variation: { גובה: "1.60" }, cost_per_item: "345" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "יוקה",
    image_path: "image_יוקה.jpeg",
  },
  {
    name: "כולל כלי מעוצבדקל ",
    variations: [{ variation: { גובה: "1.10" }, cost_per_item: "170" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "כולל כלי מעוצבדקל ",
    image_path: "image_כולל כלי מעוצבדקל .jpeg",
  },
  {
    name: "דקל אריקה גבוה ",
    variations: [{ variation: { גובה: "1.70" }, cost_per_item: "375" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל אריקה גבוה ",
    image_path: "image_דקל אריקה גבוה .jpeg",
  },
  {
    name: "אריקה בינוני  דקל ",
    variations: [{ variation: { גובה: "1.20" }, cost_per_item: "175" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "אריקה בינוני  דקל ",
    image_path: "image_אריקה בינוני  דקל .jpeg",
  },
  {
    name: "דקל אריקה נמוך ",
    variations: [{ variation: { גובה: "80" }, cost_per_item: "125" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל אריקה נמוך ",
    image_path: "image_דקל אריקה נמוך .jpeg",
  },
  {
    name: "הולנדידקל",
    variations: [{ variation: { גובה: "65" }, cost_per_item: "75" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "הולנדידקל",
    image_path: "image_הולנדידקל.jpeg",
  },
  {
    name: "'מרווה בכלי פח וינטג",
    variations: [{ variation: { גובה: "60" }, cost_per_item: "139" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "'מרווה בכלי פח וינטג",
    image_path: "image_'מרווה בכלי פח וינטג.jpeg",
  },
  {
    name: "'שרף בכלי פח וינטג",
    variations: [{ variation: { גובה: "55" }, cost_per_item: "139" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "'שרף בכלי פח וינטג",
    image_path: "image_'שרף בכלי פח וינטג.jpeg",
  },
  {
    name: "במבוק מיני",
    variations: [
      { variation: { גובה: "1" }, cost_per_item: "149", serial_number: "123" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "במבוק מיני",
    image_path: "image_במבוק מיני.jpeg",
  },
  {
    name: "במבוק קטן",
    variations: [
      {
        variation: { גובה: "1.30" },
        cost_per_item: "239",
        serial_number: "124",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "במבוק קטן",
    image_path: "image_במבוק קטן.jpeg",
  },
  {
    name: "במבוק בינוני",
    variations: [
      {
        variation: { גובה: "1.60" },
        cost_per_item: "259",
        serial_number: "164",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "במבוק בינוני",
    image_path: "image_במבוק בינוני.jpeg",
  },
  {
    name: "במבוק גדול",
    variations: [
      {
        variation: { גובה: "2.20" },
        cost_per_item: "449",
        serial_number: "165",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "במבוק גדול",
    image_path: "image_במבוק גדול.jpeg",
  },
  {
    name: "דקל בינוני",
    variations: [
      {
        variation: { גובה: "1.50" },
        cost_per_item: "215",
        serial_number: "108",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל בינוני",
    image_path: "image_דקל בינוני.jpeg",
  },
  {
    name: "דקל גדול",
    variations: [
      {
        variation: { גובה: "1.80" },
        cost_per_item: "325",
        serial_number: "118",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל גדול",
    image_path: "image_דקל גדול.jpeg",
  },
  {
    name: "יקס'צ",
    variations: [
      { variation: { גובה: "1" }, cost_per_item: "325", serial_number: "120" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "יקס'צ",
    image_path: "image_יקס'צ.jpeg",
  },
  {
    name: "ירוקהססינורה",
    variations: [
      { variation: { גובה: "90" }, cost_per_item: "235", serial_number: "160" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ירוקהססינורה",
    image_path: "image_ירוקהססינורה.jpeg",
  },
  {
    name: "מקלותסקקטו",
    variations: [
      { variation: { גובה: "80" }, cost_per_item: "159", serial_number: "161" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "מקלותסקקטו",
    image_path: "image_מקלותסקקטו.jpeg",
  },
  {
    name: "פיקוס כינורי",
    variations: [
      {
        variation: { גובה: "1.20" },
        cost_per_item: "170",
        serial_number: "162",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "פיקוס כינורי",
    image_path: "image_פיקוס כינורי.jpeg",
  },
  {
    name: "קלמניטנותץע",
    variations: [
      { variation: { גובה: "80" }, cost_per_item: "145", serial_number: "163" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "קלמניטנותץע",
    image_path: "image_קלמניטנותץע.jpeg",
  },
  {
    name: "קקטוס סן פדרו",
    variations: [
      { variation: { גובה: "75" }, cost_per_item: "230", serial_number: "159" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "קקטוס סן פדרו",
    image_path: "image_קקטוס סן פדרו.jpeg",
  },
  {
    name: "נשפך היהודי הנודד  ",
    variations: [
      { variation: { גובה: "40" }, cost_per_item: "49", serial_number: "157" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך היהודי הנודד  ",
    image_path: "image_נשפך היהודי הנודד  .jpeg",
  },
  {
    name: "פוטוסנשפך ",
    variations: [
      { variation: { גובה: "70" }, cost_per_item: "49", serial_number: "156" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "פוטוסנשפך ",
    image_path: "image_פוטוסנשפך .jpeg",
  },
  {
    name: "נשפך שעוונית זוחלת  ",
    variations: [
      { variation: { גובה: "40" }, cost_per_item: "49", serial_number: "158" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך שעוונית זוחלת  ",
    image_path: "image_נשפך שעוונית זוחלת  .jpeg",
  },
  {
    name: "נשפך שרך ירוק",
    variations: [
      { variation: { גובה: "85" }, cost_per_item: "55", serial_number: "101" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך שרך ירוק",
    image_path: "image_נשפך שרך ירוק.jpeg",
  },
  {
    name: "ערבה בוכייה",
    variations: [
      { variation: { גובה: "1.35" }, cost_per_item: "30", serial_number: "42" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ערבה בוכייה",
    image_path: "image_ערבה בוכייה.jpeg",
  },
  {
    name: "אקליפטוס בצבעים ",
    variations: [
      { variation: { גובה: "70" }, cost_per_item: "69", serial_number: "43" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "אקליפטוס בצבעים ",
    image_path: "image_אקליפטוס בצבעים .jpeg",
  },
  {
    name: "תפוז מדויק ומדושן",
    variations: [
      { variation: { גובה: "80" }, cost_per_item: "75", serial_number: "44" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "תפוז מדויק ומדושן",
    image_path: "image_תפוז מדויק ומדושן.jpeg",
  },
  {
    name: "עץ תפוז בוגר מראה ",
    variations: [
      { variation: { גובה: "1.5" }, cost_per_item: "290", serial_number: "46" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "עץ תפוז בוגר מראה ",
    image_path: "image_עץ תפוז בוגר מראה .jpeg",
  },
  {
    name: "צהובהסנסיווריה",
    variations: [
      { variation: { גובה: "90" }, cost_per_item: "185", serial_number: "26" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "צהובהסנסיווריה",
    image_path: "image_צהובהסנסיווריה.jpeg",
  },
  {
    name: "דקל טבעי",
    variations: [
      { variation: { גובה: "1.5" }, cost_per_item: "215", serial_number: "13" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל טבעי",
    image_path: "image_דקל טבעי.jpeg",
  },
  {
    name: "נשפך סוקולנטיים  ",
    variations: [
      { variation: { גובה: "55" }, cost_per_item: "45", serial_number: "410" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך סוקולנטיים  ",
    image_path: "image_נשפך סוקולנטיים  .jpeg",
  },
  {
    name: "נשפך בכלי קרמיקה  ",
    variations: [
      { variation: { גובה: "45" }, cost_per_item: "39", serial_number: "411" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך בכלי קרמיקה  ",
    image_path: "image_נשפך בכלי קרמיקה  .jpeg",
  },
  {
    name: "סוקולנטיםנשפך ",
    variations: [
      { variation: { גובה: "25" }, cost_per_item: "30", serial_number: "412" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "סוקולנטיםנשפך ",
    image_path: "image_סוקולנטיםנשפך .jpeg",
  },
  {
    name: "נשפך דסקיות טבעי ",
    variations: [
      { variation: { גובה: "1.1" }, cost_per_item: "30", serial_number: "413" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך דסקיות טבעי ",
    image_path: "image_נשפך דסקיות טבעי .jpeg",
  },
  {
    name: "נשפך עלים  פוטוס",
    variations: [
      { variation: { אורך: "2" }, cost_per_item: "49", serial_number: "414" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך עלים  פוטוס",
    image_path: "image_נשפך עלים  פוטוס.jpeg",
  },
  {
    name: "לבנדר ורוד",
    variations: [
      { variation: { גובה: "50" }, cost_per_item: "55", serial_number: "51" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "לבנדר ורוד",
    image_path: "image_לבנדר ורוד.jpeg",
  },
  {
    name: "לבנדר סגול",
    variations: [
      { variation: { גובה: "45" }, cost_per_item: "55", serial_number: "52" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "לבנדר סגול",
    image_path: "image_לבנדר סגול.jpeg",
  },
  {
    name: "עץ לימון ופרי",
    variations: [
      {
        variation: { גובה: "1.05" },
        cost_per_item: "195",
        serial_number: "55",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "עץ לימון ופרי",
    image_path: "image_עץ לימון ופרי.jpeg",
  },
  {
    name: "דקל וושינגטוניה  ",
    variations: [
      {
        variation: { גובה: "1.65" },
        cost_per_item: "325",
        serial_number: "56",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל וושינגטוניה  ",
    image_path: "image_דקל וושינגטוניה  .jpeg",
  },
  {
    name: "דקל וושינגטוניה",
    variations: [
      {
        variation: { גובה: "1.35" },
        cost_per_item: "215",
        serial_number: "57",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל וושינגטוניה",
    image_path: "image_דקל וושינגטוניה.jpeg",
  },
  {
    name: "ירוקה בכליסנסיווריה",
    variations: [
      { variation: { גובה: "60" }, cost_per_item: "75", serial_number: "58" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ירוקה בכליסנסיווריה",
    image_path: "image_ירוקה בכליסנסיווריה.jpeg",
  },
  {
    name: "סוקולנט בכלי",
    variations: [
      { variation: { גובה: "60" }, cost_per_item: "49", serial_number: "59" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "סוקולנט בכלי",
    image_path: "image_סוקולנט בכלי.jpeg",
  },
  {
    name: "סוקולנט ירוק חום  ",
    variations: [
      { variation: { גובה: "60" }, cost_per_item: "49", serial_number: "510" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "סוקולנט ירוק חום  ",
    image_path: "image_סוקולנט ירוק חום  .jpeg",
  },
  {
    name: "אנטוריום נשפך",
    variations: [
      {
        variation: { גובה: "1.35" },
        cost_per_item: "39",
        serial_number: "511",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "אנטוריום נשפך",
    image_path: "image_אנטוריום נשפך.jpeg",
  },
  {
    name: "ציפור גן עדן",
    variations: [
      { variation: { גובה: "1.6" }, cost_per_item: "395", serial_number: "24" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ציפור גן עדן",
    image_path: "image_ציפור גן עדן.jpeg",
  },
  {
    name: "עץ ניצנים אדומים",
    variations: [
      {
        variation: { גובה: "1.25" },
        cost_per_item: "195",
        serial_number: "47",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "עץ ניצנים אדומים",
    image_path: "image_עץ ניצנים אדומים.jpeg",
  },
  {
    name: "ומדושןתפוז מדויק ",
    variations: [{ variation: { גובה: "80" }, cost_per_item: "75" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ומדושןתפוז מדויק ",
    image_path: "image_ומדושןתפוז מדויק .jpeg",
  },
  {
    name: "עץ עלים מראה טבעי  ",
    variations: [{ variation: { גובה: "125" }, cost_per_item: "195" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "עץ עלים מראה טבעי  ",
    image_path: "image_עץ עלים מראה טבעי  .jpeg",
  },
][
  ({
    name: "מונסטרה",
    variations: [{ variation: { גובה: "70" }, cost_per_item: "80" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "מונסטרה",
    image_path: "image_מונסטרה.jpeg",
  },
  {
    name: "היוקקקטוס",
    variations: [{ variation: { גובה: "1.65" }, cost_per_item: "375" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "היוקקקטוס",
    image_path: "image_היוקקקטוס.jpeg",
  },
  {
    name: "יוקה",
    variations: [{ variation: { גובה: "1.60" }, cost_per_item: "345" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "יוקה",
    image_path: "image_יוקה.jpeg",
  },
  {
    name: "כולל כלי מעוצבדקל ",
    variations: [{ variation: { גובה: "1.10" }, cost_per_item: "170" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "כולל כלי מעוצבדקל ",
    image_path: "image_כולל כלי מעוצבדקל .jpeg",
  },
  {
    name: "דקל אריקה גבוה ",
    variations: [{ variation: { גובה: "1.70" }, cost_per_item: "375" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל אריקה גבוה ",
    image_path: "image_דקל אריקה גבוה .jpeg",
  },
  {
    name: "אריקה בינוני  דקל ",
    variations: [{ variation: { גובה: "1.20" }, cost_per_item: "175" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "אריקה בינוני  דקל ",
    image_path: "image_אריקה בינוני  דקל .jpeg",
  },
  {
    name: "דקל אריקה נמוך ",
    variations: [{ variation: { גובה: "80" }, cost_per_item: "125" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל אריקה נמוך ",
    image_path: "image_דקל אריקה נמוך .jpeg",
  },
  {
    name: "הולנדידקל",
    variations: [{ variation: { גובה: "65" }, cost_per_item: "75" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "הולנדידקל",
    image_path: "image_הולנדידקל.jpeg",
  },
  {
    name: "'מרווה בכלי פח וינטג",
    variations: [{ variation: { גובה: "60" }, cost_per_item: "139" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "'מרווה בכלי פח וינטג",
    image_path: "image_'מרווה בכלי פח וינטג.jpeg",
  },
  {
    name: "'שרף בכלי פח וינטג",
    variations: [{ variation: { גובה: "55" }, cost_per_item: "139" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "'שרף בכלי פח וינטג",
    image_path: "image_'שרף בכלי פח וינטג.jpeg",
  },
  {
    name: "במבוק מיני",
    variations: [
      { variation: { גובה: "1" }, cost_per_item: "149", serial_number: "123" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "במבוק מיני",
    image_path: "image_במבוק מיני.jpeg",
  },
  {
    name: "במבוק קטן",
    variations: [
      {
        variation: { גובה: "1.30" },
        cost_per_item: "239",
        serial_number: "124",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "במבוק קטן",
    image_path: "image_במבוק קטן.jpeg",
  },
  {
    name: "במבוק בינוני",
    variations: [
      {
        variation: { גובה: "1.60" },
        cost_per_item: "259",
        serial_number: "164",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "במבוק בינוני",
    image_path: "image_במבוק בינוני.jpeg",
  },
  {
    name: "במבוק גדול",
    variations: [
      {
        variation: { גובה: "2.20" },
        cost_per_item: "449",
        serial_number: "165",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "במבוק גדול",
    image_path: "image_במבוק גדול.jpeg",
  },
  {
    name: "דקל בינוני",
    variations: [
      {
        variation: { גובה: "1.50" },
        cost_per_item: "215",
        serial_number: "108",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל בינוני",
    image_path: "image_דקל בינוני.jpeg",
  },
  {
    name: "דקל גדול",
    variations: [
      {
        variation: { גובה: "1.80" },
        cost_per_item: "325",
        serial_number: "118",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל גדול",
    image_path: "image_דקל גדול.jpeg",
  },
  {
    name: "יקס'צ",
    variations: [
      { variation: { גובה: "1" }, cost_per_item: "325", serial_number: "120" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "יקס'צ",
    image_path: "image_יקס'צ.jpeg",
  },
  {
    name: "ירוקהססינורה",
    variations: [
      { variation: { גובה: "90" }, cost_per_item: "235", serial_number: "160" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ירוקהססינורה",
    image_path: "image_ירוקהססינורה.jpeg",
  },
  {
    name: "מקלותסקקטו",
    variations: [
      { variation: { גובה: "80" }, cost_per_item: "159", serial_number: "161" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "מקלותסקקטו",
    image_path: "image_מקלותסקקטו.jpeg",
  },
  {
    name: "פיקוס כינורי",
    variations: [
      {
        variation: { גובה: "1.20" },
        cost_per_item: "170",
        serial_number: "162",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "פיקוס כינורי",
    image_path: "image_פיקוס כינורי.jpeg",
  },
  {
    name: "קלמניטנותץע",
    variations: [
      { variation: { גובה: "80" }, cost_per_item: "145", serial_number: "163" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "קלמניטנותץע",
    image_path: "image_קלמניטנותץע.jpeg",
  },
  {
    name: "קקטוס סן פדרו",
    variations: [
      { variation: { גובה: "75" }, cost_per_item: "230", serial_number: "159" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "קקטוס סן פדרו",
    image_path: "image_קקטוס סן פדרו.jpeg",
  },
  {
    name: "נשפך היהודי הנודד  ",
    variations: [
      { variation: { גובה: "40" }, cost_per_item: "49", serial_number: "157" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך היהודי הנודד  ",
    image_path: "image_נשפך היהודי הנודד  .jpeg",
  },
  {
    name: "פוטוסנשפך ",
    variations: [
      { variation: { גובה: "70" }, cost_per_item: "49", serial_number: "156" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "פוטוסנשפך ",
    image_path: "image_פוטוסנשפך .jpeg",
  },
  {
    name: "נשפך שעוונית זוחלת  ",
    variations: [
      { variation: { גובה: "40" }, cost_per_item: "49", serial_number: "158" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך שעוונית זוחלת  ",
    image_path: "image_נשפך שעוונית זוחלת  .jpeg",
  },
  {
    name: "נשפך שרך ירוק",
    variations: [
      { variation: { גובה: "85" }, cost_per_item: "55", serial_number: "101" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך שרך ירוק",
    image_path: "image_נשפך שרך ירוק.jpeg",
  },
  {
    name: "ערבה בוכייה",
    variations: [
      { variation: { גובה: "1.35" }, cost_per_item: "30", serial_number: "42" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ערבה בוכייה",
    image_path: "image_ערבה בוכייה.jpeg",
  },
  {
    name: "אקליפטוס בצבעים ",
    variations: [
      { variation: { גובה: "70" }, cost_per_item: "69", serial_number: "43" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "אקליפטוס בצבעים ",
    image_path: "image_אקליפטוס בצבעים .jpeg",
  },
  {
    name: "תפוז מדויק ומדושן",
    variations: [
      { variation: { גובה: "80" }, cost_per_item: "75", serial_number: "44" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "תפוז מדויק ומדושן",
    image_path: "image_תפוז מדויק ומדושן.jpeg",
  },
  {
    name: "עץ תפוז בוגר מראה ",
    variations: [
      { variation: { גובה: "1.5" }, cost_per_item: "290", serial_number: "46" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "עץ תפוז בוגר מראה ",
    image_path: "image_עץ תפוז בוגר מראה .jpeg",
  },
  {
    name: "צהובהסנסיווריה",
    variations: [
      { variation: { גובה: "90" }, cost_per_item: "185", serial_number: "26" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "צהובהסנסיווריה",
    image_path: "image_צהובהסנסיווריה.jpeg",
  },
  {
    name: "דקל טבעי",
    variations: [
      { variation: { גובה: "1.5" }, cost_per_item: "215", serial_number: "13" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל טבעי",
    image_path: "image_דקל טבעי.jpeg",
  },
  {
    name: "נשפך סוקולנטיים  ",
    variations: [
      { variation: { גובה: "55" }, cost_per_item: "45", serial_number: "410" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך סוקולנטיים  ",
    image_path: "image_נשפך סוקולנטיים  .jpeg",
  },
  {
    name: "נשפך בכלי קרמיקה  ",
    variations: [
      { variation: { גובה: "45" }, cost_per_item: "39", serial_number: "411" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך בכלי קרמיקה  ",
    image_path: "image_נשפך בכלי קרמיקה  .jpeg",
  },
  {
    name: "סוקולנטיםנשפך ",
    variations: [
      { variation: { גובה: "25" }, cost_per_item: "30", serial_number: "412" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "סוקולנטיםנשפך ",
    image_path: "image_סוקולנטיםנשפך .jpeg",
  },
  {
    name: "נשפך דסקיות טבעי ",
    variations: [
      { variation: { גובה: "1.1" }, cost_per_item: "30", serial_number: "413" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך דסקיות טבעי ",
    image_path: "image_נשפך דסקיות טבעי .jpeg",
  },
  {
    name: "נשפך עלים  פוטוס",
    variations: [
      { variation: { אורך: "2" }, cost_per_item: "49", serial_number: "414" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "נשפך עלים  פוטוס",
    image_path: "image_נשפך עלים  פוטוס.jpeg",
  },
  {
    name: "לבנדר ורוד",
    variations: [
      { variation: { גובה: "50" }, cost_per_item: "55", serial_number: "51" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "לבנדר ורוד",
    image_path: "image_לבנדר ורוד.jpeg",
  },
  {
    name: "לבנדר סגול",
    variations: [
      { variation: { גובה: "45" }, cost_per_item: "55", serial_number: "52" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "לבנדר סגול",
    image_path: "image_לבנדר סגול.jpeg",
  },
  {
    name: "עץ לימון ופרי",
    variations: [
      {
        variation: { גובה: "1.05" },
        cost_per_item: "195",
        serial_number: "55",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "עץ לימון ופרי",
    image_path: "image_עץ לימון ופרי.jpeg",
  },
  {
    name: "דקל וושינגטוניה  ",
    variations: [
      {
        variation: { גובה: "1.65" },
        cost_per_item: "325",
        serial_number: "56",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל וושינגטוניה  ",
    image_path: "image_דקל וושינגטוניה  .jpeg",
  },
  {
    name: "דקל וושינגטוניה",
    variations: [
      {
        variation: { גובה: "1.35" },
        cost_per_item: "215",
        serial_number: "57",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "דקל וושינגטוניה",
    image_path: "image_דקל וושינגטוניה.jpeg",
  },
  {
    name: "ירוקה בכליסנסיווריה",
    variations: [
      { variation: { גובה: "60" }, cost_per_item: "75", serial_number: "58" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ירוקה בכליסנסיווריה",
    image_path: "image_ירוקה בכליסנסיווריה.jpeg",
  },
  {
    name: "סוקולנט בכלי",
    variations: [
      { variation: { גובה: "60" }, cost_per_item: "49", serial_number: "59" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "סוקולנט בכלי",
    image_path: "image_סוקולנט בכלי.jpeg",
  },
  {
    name: "סוקולנט ירוק חום  ",
    variations: [
      { variation: { גובה: "60" }, cost_per_item: "49", serial_number: "510" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "סוקולנט ירוק חום  ",
    image_path: "image_סוקולנט ירוק חום  .jpeg",
  },
  {
    name: "אנטוריום נשפך",
    variations: [
      {
        variation: { גובה: "1.35" },
        cost_per_item: "39",
        serial_number: "511",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "אנטוריום נשפך",
    image_path: "image_אנטוריום נשפך.jpeg",
  },
  {
    name: "ציפור גן עדן",
    variations: [
      { variation: { גובה: "1.6" }, cost_per_item: "395", serial_number: "24" },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ציפור גן עדן",
    image_path: "image_ציפור גן עדן.jpeg",
  },
  {
    name: "עץ ניצנים אדומים",
    variations: [
      {
        variation: { גובה: "1.25" },
        cost_per_item: "195",
        serial_number: "47",
      },
    ],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "עץ ניצנים אדומים",
    image_path: "image_עץ ניצנים אדומים.jpeg",
  },
  {
    name: "ומדושןתפוז מדויק ",
    variations: [{ variation: { גובה: "80" }, cost_per_item: "75" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "ומדושןתפוז מדויק ",
    image_path: "image_ומדושןתפוז מדויק .jpeg",
  },
  {
    name: "עץ עלים מראה טבעי  ",
    variations: [{ variation: { גובה: "125" }, cost_per_item: "195" }],
    currency: "ils",
    category: "צמחים",
    subcategory: "צמחים",
    description: "עץ עלים מראה טבעי  ",
    image_path: "image_עץ עלים מראה טבעי  .jpeg",
  })
];
